In [67]:
import pandas as pd
import os
import numpy as np

pd.options.mode.chained_assignment = None 
pd.set_option('display.max_columns', None) # Display all columns
pd.set_option('display.width', 1000)

In [2]:
def col_list(csv_file):
    df = pd.read_csv(f'data/{csv_file}')
    return df.columns.tolist()

In [3]:
csv_list = os.listdir('data')
csv_list.remove(".gitattributes")
for i in range(len(csv_list)):
    csv = csv_list[i]
    print(f"{i + 1}: {csv} - Columns: {col_list(csv)}")

1: MNCAATourneyDetailedResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
2: WNCAATourneySlots.csv - Columns: ['Season', 'Slot', 'StrongSeed', 'WeakSeed']
3: MNCAATourneyCompactResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
4: MSeasons.csv - Columns: ['Season', 'DayZero', 'RegionW', 'RegionX', 'RegionY', 'RegionZ']
5: WTeams.csv - Columns: ['TeamID', 'TeamName']
6: MRegularSeasonDetailedResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
7: WNCAATourneyDetailedResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
8: MNCAATourneySlots.csv - Columns: ['Season', 'Slot', 'StrongSeed', 'WeakSeed']
9: MConferenceTourneyGames.csv - Columns: ['Season', 'ConfAbbrev', 'DayNum', 'WTeamID', 'LTeamID']
10: WNCAATourneyCompactResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
11: WSeasons.csv - Columns: ['Season', 'DayZero', 'RegionW', 'RegionX', 'RegionY', 'RegionZ']
12: WRegularSeasonCompactResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
13: WRegularSeasonDetailedResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
14: MRegularSeasonCompactResults.csv - Columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
15: WNCAATourneySeeds.csv - Columns: ['Season', 'Seed', 'TeamID']
16: MNCAATourneySeedRoundSlots.csv - Columns: ['Seed', 'GameRound', 'GameSlot', 'EarlyDayNum', 'LateDayNum']
17: WConferenceTourneyGames.csv - Columns: ['Season', 'ConfAbbrev', 'DayNum', 'WTeamID', 'LTeamID']
18: WTeamConferences.csv - Columns: ['Season', 'TeamID', 'ConfAbbrev']
19: MTeamConferences.csv - Columns: ['Season', 'TeamID', 'ConfAbbrev']
20: MTeamCoaches.csv - Columns: ['Season', 'TeamID', 'FirstDayNum', 'LastDayNum', 'CoachName']
21: MMasseyOrdinals.csv - Columns: ['Season', 'RankingDayNum', 'SystemName', 'TeamID', 'OrdinalRank']
22: MTeams.csv - Columns: ['TeamID', 'TeamName', 'FirstD1Season', 'LastD1Season']
23: MNCAATourneySeeds.csv - Columns: ['Season', 'Seed', 'TeamID']

In [4]:
mens_data = [csv for csv in csv_list if csv[0] == 'M']
womens_data = [csv for csv in csv_list if csv[0] == 'W']

print("MENS INFO:\n--------------------------")

for mf in mens_data:
    print(f"{mf[:-4]}: {col_list(mf)}")

print("\nWOMENS INFO:\n--------------------------")

for wf in womens_data:
    print(f"{wf[:-4]}: {col_list(wf)}")

MENS INFO:
--------------------------
MNCAATourneyDetailedResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
MNCAATourneyCompactResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
MSeasons: ['Season', 'DayZero', 'RegionW', 'RegionX', 'RegionY', 'RegionZ']
MRegularSeasonDetailedResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
MNCAATourneySlots: ['Season', 'Slot', 'StrongSeed', 'WeakSeed']
MConferenceTourneyGames: ['Season', 'ConfAbbrev', 'DayNum', 'WTeamID', 'LTeamID']
MRegularSeasonCompactResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
MNCAATourneySeedRoundSlots: ['Seed', 'GameRound', 'GameSlot', 'EarlyDayNum', 'LateDayNum']
MTeamConferences: ['Season', 'TeamID', 'ConfAbbrev']
MTeamCoaches: ['Season', 'TeamID', 'FirstDayNum', 'LastDayNum', 'CoachName']
MMasseyOrdinals: ['Season', 'RankingDayNum', 'SystemName', 'TeamID', 'OrdinalRank']
MTeams: ['TeamID', 'TeamName', 'FirstD1Season', 'LastD1Season']
MNCAATourneySeeds: ['Season', 'Seed', 'TeamID']

WOMENS INFO:
--------------------------
WNCAATourneySlots: ['Season', 'Slot', 'StrongSeed', 'WeakSeed']
WTeams: ['TeamID', 'TeamName']
WNCAATourneyDetailedResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
WNCAATourneyCompactResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
WSeasons: ['Season', 'DayZero', 'RegionW', 'RegionX', 'RegionY', 'RegionZ']
WRegularSeasonCompactResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']
WRegularSeasonDetailedResults: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR', 'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3', 'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF']
WNCAATourneySeeds: ['Season', 'Seed', 'TeamID']
WConferenceTourneyGames: ['Season', 'ConfAbbrev', 'DayNum', 'WTeamID', 'LTeamID']
WTeamConferences: ['Season', 'TeamID', 'ConfAbbrev']

In [21]:
# Load the data
M_regular_season_results = pd.read_csv("data/MRegularSeasonDetailedResults.csv")
M_tourney_results = pd.read_csv("data/MNCAATourneyDetailedResults.csv")
M_seeds = pd.read_csv("data/MNCAATourneySeeds.csv")

In [22]:
M_regular_season_results

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124524,2026,132,1335,88,1463,84,N,1,29,64,...,24,13,17,17,24,23,9,9,4,16
124525,2026,132,1345,80,1276,72,N,0,30,57,...,24,5,6,11,22,15,7,2,3,18
124526,2026,132,1378,70,1455,55,N,0,23,61,...,19,13,20,12,27,8,14,7,7,19
124527,2026,132,1433,70,1173,62,N,0,23,57,...,21,9,17,8,31,16,11,3,4,18
124528,2026,132,1465,63,1430,61,A,0,22,58,...,8,14,24,9,24,11,14,6,3,11

In [23]:
# Only consider recent data
season = 2003 
M_regular_season_results = M_regular_season_results.loc[M_regular_season_results["Season"] >= season]
M_tourney_results = M_tourney_results.loc[M_tourney_results["Season"] >= season]
M_seeds = M_seeds.loc[M_seeds["Season"] >= season]

In [24]:
# See the data
M_regular_season_results

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124524,2026,132,1335,88,1463,84,N,1,29,64,...,24,13,17,17,24,23,9,9,4,16
124525,2026,132,1345,80,1276,72,N,0,30,57,...,24,5,6,11,22,15,7,2,3,18
124526,2026,132,1378,70,1455,55,N,0,23,61,...,19,13,20,12,27,8,14,7,7,19
124527,2026,132,1433,70,1173,62,N,0,23,57,...,21,9,17,8,31,16,11,3,4,18
124528,2026,132,1465,63,1430,61,A,0,22,58,...,8,14,24,9,24,11,14,6,3,11

In [25]:
M_tourney_results

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,2025,146,1120,70,1277,64,N,0,26,61,...,23,13,16,11,27,12,9,5,5,18
1445,2025,146,1222,69,1397,50,N,0,28,66,...,29,15,20,11,23,12,9,3,2,9
1446,2025,152,1196,79,1120,73,N,0,25,53,...,25,16,23,9,20,11,12,11,3,22
1447,2025,152,1222,70,1181,67,N,0,23,61,...,17,18,23,10,19,14,7,7,4,16
1448,2025,154,1196,65,1222,63,N,0,21,53,...,25,9,14,13,22,5,8,5,6,19

In [38]:
M_seeds

      Season Seed  TeamID
1154    2003  W01    1328
1155    2003  W02    1448
1156    2003  W03    1393
1157    2003  W04    1257
1158    2003  W05    1280
...      ...  ...     ...
2689    2026  Z12    1219
2690    2026  Z13    1218
2691    2026  Z14    1244
2692    2026  Z15    1474
2693    2026  Z16    1254

[1540 rows x 3 columns]

In [39]:
# helper function to visualize a specific team's season

def M_view_season(team_id, season):

    reg_res = M_regular_season_results.loc[
        (M_regular_season_results["Season"] == season)
        & ((M_regular_season_results["WTeamID"] == team_id) | (M_regular_season_results["LTeamID"] == team_id))]
    tour_res = M_tourney_results.loc[
        (M_tourney_results["Season"] == season)
        & ((M_tourney_results["WTeamID"] == team_id) | (M_tourney_results["LTeamID"] == team_id))
    ]

    reg_res["result"] = np.where(reg_res["WTeamID"] == team_id, "W", "L")
    tour_res["result"] = np.where(tour_res["WTeamID"] == team_id, "W", "L")
    reg_res["type"] = "regular season"
    tour_res["type"] = "tournament"

    summary = pd.concat([reg_res, tour_res])

    return summary[["DayNum", "WScore", "LScore", "type", "result"]]

M_view_season(team_id=1181, season=2024) # Duke, 2024 (R64: W, R32: W, R16: W, E8 - L)

        DayNum  WScore  LScore            type result
107660       0      92      54  regular season      W
107806       4      78      73  regular season      L
107990       8      74      65  regular season      W
108108      11      90      60  regular season      W
108349      15      95      66  regular season      W
108478      18      80      62  regular season      W
108687      23      80      75  regular season      L
108832      26      72      68  regular season      L
109072      33      80      56  regular season      W
109196      36      89      68  regular season      W
109434      44      78      70  regular season      W
109684      54     106      69  regular season      W
109786      57      86      66  regular season      W
109949      61      67      59  regular season      W
110105      64      75      53  regular season      W
110282      68      84      79  regular season      W
110667      75      80      76  regular season      L
110762      78      83      69  regular season      W
110932      82      72      71  regular season      W
111070      84      77      67  regular season      W
111316      89      93      84  regular season      L
111463      93      71      53  regular season      W
111605      96      80      65  regular season      W
111740      98      77      69  regular season      W
111934     103      76      67  regular season      W
112117     107      84      55  regular season      W
112365     110      83      79  regular season      L
112462     114      84      59  regular season      W
112612     117      73      48  regular season      W
112738     119      79      64  regular season      W
112971     124      84      79  regular season      L
113148     129      74      69  regular season      L
1340       137      64      47      tournament      W
1362       139      93      55      tournament      W
1371       144      54      51      tournament      W
1377       146      76      64      tournament      L

In [42]:
# helper function to get a team's seed based on id and season
def M_get_seed(team_id, season):
    return M_seeds.loc[(M_seeds["Season"] == season) & (M_seeds["TeamID"] == team_id)]

M_get_seed(team_id=1181, season=2024) # Duke was a 4th seed in 2024

      Season Seed  TeamID
2544    2024  Z04    1181

In [74]:
def prepare_data(results_df):
    
    # remove WLoc from features - Location - Home (H), Away (A), Neutral (N)
    all_but_WLoc = ["Season", "DayNum", "LTeamID", "LScore", "WTeamID", "WScore", "NumOT",
            "LFGM", "LFGA", "LFGM3", "LFGA3", "LFTM", "LFTA", "LOR", "LDR", "LAst", "LTO", "LStl", "LBlk", "LPF",
            "WFGM", "WFGA", "WFGM3", "WFGA3", "WFTM", "WFTA", "WOR", "WDR", "WAst", "WTO", "WStl", "WBlk", "WPF"]
    
    results_df = results_df[all_but_WLoc]

    # creates a column for OT adjustment factor based on NumOT column
    ot_adjust = (40 + 5 * results_df["NumOT"]) / 40

    # specify stats which need to be adjusted
    cols_adjust = ["LScore", "WScore", 
               "LFGM", "LFGA", "LFGM3", "LFGA3", "LFTM", "LFTA", "LOR", "LDR", "LAst", "LTO", "LStl", "LBlk", "LPF",
               "WFGM", "WFGA", "WFGM3", "WFGA3", "WFTM", "WFTA", "WOR", "WDR", "WAst", "WTO", "WStl", "WBlk", "WPF"]

    # for each column that needs to be adjusted, adjust by corresponding adjustment factor
    for col in cols_adjust:
        results_df[col] = results_df[col] / ot_adjust

    # need to have a copy for each result for each team's persepctive (helpful during aggregation)
    # Use T1 and T2 for column standardization instead of W and L
    results_df_symmetric = results_df.copy()
    results_df.columns = [x.replace("W", "T1_").replace("L", "T2_") for x in list(results_df.columns)]
    results_df_symmetric.columns =  [x.replace("L", "T1_").replace("W", "T2_") for x in list(results_df_symmetric.columns)]

    # combine both perspective results
    combined = pd.concat([results_df, results_df_symmetric]).reset_index(drop = True)

    # add point differential for game
    combined["PointDiff"] = combined["T1_Score"] - combined["T2_Score"]

    # add indicator for win for game
    combined["win"] = (combined["PointDiff"] > 0) * 1

    return combined

M_reg_data = prepare_data(M_regular_season_results)

print("Men's Regular Season Detailed Results:")
print(M_reg_data)

M_tourney_data = prepare_data(M_tourney_results)

print("Men's Tourney Detailed Results:")
print(M_reg_data)

Men's Regular Season Detailed Results:
        Season  DayNum  T2_TeamID   T2_Score  T1_TeamID   T1_Score  NumOT     T2_FGM     T2_FGA    T2_FGM3    T2_FGA3     T2_FTM     T2_FTA      T2_OR      T2_DR     T2_Ast      T2_TO     T2_Stl    T2_Blk      T2_PF     T1_FGM     T1_FGA  T1_FGM3    T1_FGA3     T1_FTM     T1_FTA      T1_OR      T1_DR     T1_Ast  T1_TO  T1_Stl    T1_Blk      T1_PF  PointDiff  win
0         2003      10       1328  62.000000       1104  68.000000      0  22.000000  53.000000   2.000000  10.000000  16.000000  22.000000  10.000000  22.000000   8.000000  18.000000   9.000000  2.000000  20.000000  27.000000  58.000000      3.0  14.000000  11.000000  18.000000  14.000000  24.000000  13.000000   23.0     7.0  1.000000  22.000000   6.000000    1
1         2003      10       1393  63.000000       1272  70.000000      0  24.000000  67.000000   6.000000  24.000000   9.000000  20.000000  20.000000  25.000000   7.000000  12.000000   8.000000  6.000000  16.000000  26.000000  62.000000      8.0  20.000000  10.000000  19.000000  15.000000  28.000000  16.000000   13.0     4.0  4.000000  18.000000   7.000000    1
2         2003      11       1437  61.000000       1266  73.000000      0  22.000000  73.000000   3.000000  26.000000  14.000000  23.000000  31.000000  22.000000   9.000000  12.000000   2.000000  5.000000  23.000000  24.000000  58.000000      8.0  18.000000  17.000000  29.000000  17.000000  26.000000  15.000000   10.0     5.0  2.000000  25.000000  12.000000    1
3         2003      11       1457  50.000000       1296  56.000000      0  18.000000  49.000000   6.000000  22.000000   8.000000  15.000000  17.000000  20.000000   9.000000  19.000000   4.000000  3.000000  23.000000  18.000000  38.000000      3.0   9.000000  17.000000  31.000000   6.000000  19.000000  11.000000   12.0    14.0  2.000000  18.000000   6.000000    1
4         2003      11       1208  71.000000       1400  77.000000      0  24.000000  62.000000   6.000000  16.000000  17.000000  27.000000  21.000000  15.000000  12.000000  10.000000   7.000000  1.000000  14.000000  30.000000  61.000000      6.0  14.000000  11.000000  13.000000  17.000000  22.000000  12.000000   14.0     4.0  4.000000  20.000000   6.000000    1
...        ...     ...        ...        ...        ...        ...    ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...       ...        ...        ...        ...      ...        ...        ...        ...        ...        ...        ...    ...     ...       ...        ...        ...  ...
249053    2026     132       1335  78.222222       1463  74.666667      1  25.777778  56.888889  12.444444  24.888889  14.222222  14.222222   9.777778  23.111111  15.111111  11.555556   4.444444  3.555556  14.222222  27.555556  63.111111      8.0  21.333333  11.555556  15.111111  15.111111  21.333333  20.444444    8.0     8.0  3.555556  14.222222  -3.555556    0
249054    2026     132       1345  80.000000       1276  72.000000      0  30.000000  57.000000   4.000000  14.000000  16.000000  22.000000   7.000000  22.000000  21.000000   2.000000   4.000000  5.000000  13.000000  30.000000  64.000000      7.0  24.000000   5.000000   6.000000  11.000000  22.000000  15.000000    7.0     2.0  3.000000  18.000000  -8.000000    0
249055    2026     132       1378  70.000000       1455  55.000000      0  23.000000  61.000000   6.000000  22.000000  18.000000  23.000000  14.000000  27.000000  13.000000  10.000000  10.000000  3.000000  20.000000  19.000000  56.000000      4.0  19.000000  13.000000  20.000000  12.000000  27.000000   8.000000   14.0     7.0  7.000000  19.000000 -15.000000    0
249056    2026     132       1433  70.000000       1173  62.000000      0  23.000000  57.000000  11.000000  24.000000  13.000000  19.000000   6.000000  28.000000  12.000000   5.000000   9.000000  4.000000  18.000000  23.000000  53.000000      7.0  21.000000   9.000000  17.000000   8.000000  31.000000  16.000000   11.0     3.0  4.000000  18.000000  -8.000000    0
249057    2026     132       1465  63.000000       1430  61.000000      0  22.000000  58.000000   9.000000  26.000000  10.000000  11.000000  10.000000  25.000000   9.000000  13.000000   7.000000  2.000000  20.000000  22.000000  50.000000      3.0   8.000000  14.000000  24.000000   9.000000  24.000000  11.000000   14.0     6.0  3.000000  11.000000  -2.000000    0

[249058 rows x 35 columns]
Men's Tourney Detailed Results:
        Season  DayNum  T2_TeamID   T2_Score  T1_TeamID   T1_Score  NumOT     T2_FGM     T2_FGA    T2_FGM3    T2_FGA3     T2_FTM     T2_FTA      T2_OR      T2_DR     T2_Ast      T2_TO     T2_Stl    T2_Blk      T2_PF     T1_FGM     T1_FGA  T1_FGM3    T1_FGA3     T1_FTM     T1_FTA      T1_OR      T1_DR     T1_Ast  T1_TO  T1_Stl    T1_Blk      T1_PF  PointDiff  win
0         2003      10       1328  62.000000       1104  68.000000      0  22.000000  53.000000   2.000000  10.000000  16.000000  22.000000  10.000000  22.000000   8.000000  18.000000   9.000000  2.000000  20.000000  27.000000  58.000000      3.0  14.000000  11.000000  18.000000  14.000000  24.000000  13.000000   23.0     7.0  1.000000  22.000000   6.000000    1
1         2003      10       1393  63.000000       1272  70.000000      0  24.000000  67.000000   6.000000  24.000000   9.000000  20.000000  20.000000  25.000000   7.000000  12.000000   8.000000  6.000000  16.000000  26.000000  62.000000      8.0  20.000000  10.000000  19.000000  15.000000  28.000000  16.000000   13.0     4.0  4.000000  18.000000   7.000000    1
2         2003      11       1437  61.000000       1266  73.000000      0  22.000000  73.000000   3.000000  26.000000  14.000000  23.000000  31.000000  22.000000   9.000000  12.000000   2.000000  5.000000  23.000000  24.000000  58.000000      8.0  18.000000  17.000000  29.000000  17.000000  26.000000  15.000000   10.0     5.0  2.000000  25.000000  12.000000    1
3         2003      11       1457  50.000000       1296  56.000000      0  18.000000  49.000000   6.000000  22.000000   8.000000  15.000000  17.000000  20.000000   9.000000  19.000000   4.000000  3.000000  23.000000  18.000000  38.000000      3.0   9.000000  17.000000  31.000000   6.000000  19.000000  11.000000   12.0    14.0  2.000000  18.000000   6.000000    1
4         2003      11       1208  71.000000       1400  77.000000      0  24.000000  62.000000   6.000000  16.000000  17.000000  27.000000  21.000000  15.000000  12.000000  10.000000   7.000000  1.000000  14.000000  30.000000  61.000000      6.0  14.000000  11.000000  13.000000  17.000000  22.000000  12.000000   14.0     4.0  4.000000  20.000000   6.000000    1
...        ...     ...        ...        ...        ...        ...    ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...        ...       ...        ...        ...        ...      ...        ...        ...        ...        ...        ...        ...    ...     ...       ...        ...        ...  ...
249053    2026     132       1335  78.222222       1463  74.666667      1  25.777778  56.888889  12.444444  24.888889  14.222222  14.222222   9.777778  23.111111  15.111111  11.555556   4.444444  3.555556  14.222222  27.555556  63.111111      8.0  21.333333  11.555556  15.111111  15.111111  21.333333  20.444444    8.0     8.0  3.555556  14.222222  -3.555556    0
249054    2026     132       1345  80.000000       1276  72.000000      0  30.000000  57.000000   4.000000  14.000000  16.000000  22.000000   7.000000  22.000000  21.000000   2.000000   4.000000  5.000000  13.000000  30.000000  64.000000      7.0  24.000000   5.000000   6.000000  11.000000  22.000000  15.000000    7.0     2.0  3.000000  18.000000  -8.000000    0
249055    2026     132       1378  70.000000       1455  55.000000      0  23.000000  61.000000   6.000000  22.000000  18.000000  23.000000  14.000000  27.000000  13.000000  10.000000  10.000000  3.000000  20.000000  19.000000  56.000000      4.0  19.000000  13.000000  20.000000  12.000000  27.000000   8.000000   14.0     7.0  7.000000  19.000000 -15.000000    0
249056    2026     132       1433  70.000000       1173  62.000000      0  23.000000  57.000000  11.000000  24.000000  13.000000  19.000000   6.000000  28.000000  12.000000   5.000000   9.000000  4.000000  18.000000  23.000000  53.000000      7.0  21.000000   9.000000  17.000000   8.000000  31.000000  16.000000   11.0     3.0  4.000000  18.000000  -8.000000    0
249057    2026     132       1465  63.000000       1430  61.000000      0  22.000000  58.000000   9.000000  26.000000  10.000000  11.000000  10.000000  25.000000   9.000000  13.000000   7.000000  2.000000  20.000000  22.000000  50.000000      3.0   8.000000  14.000000  24.000000   9.000000  24.000000  11.000000   14.0     6.0  3.000000  11.000000  -2.000000    0

[249058 rows x 35 columns]

In [76]:
# Sanity check to ensure that preprocessing has worked successfully - check a specific outcome for symmetry
season = M_reg_data["Season"] == 2025
T1, T2 = 1182, 1433
match1 = (M_reg_data["T1_TeamID"] == T1) & (M_reg_data["T2_TeamID"] == T2)
match2 = (M_reg_data["T1_TeamID"] == T2) & (M_reg_data["T2_TeamID"] == T1)

M_reg_data.loc[season & (match1 | match2)]

        Season  DayNum  T2_TeamID  T2_Score  T1_TeamID  T1_Score  NumOT  T2_FGM  T2_FGA  T2_FGM3  T2_FGA3  T2_FTM  T2_FTA  T2_OR  T2_DR  T2_Ast  T2_TO  T2_Stl  T2_Blk  T2_PF  T1_FGM  T1_FGA  T1_FGM3  T1_FGA3  T1_FTM  T1_FTA  T1_OR  T1_DR  T1_Ast  T1_TO  T1_Stl  T1_Blk  T1_PF  PointDiff  win
118444    2025     120       1182      62.0       1433      71.0      0    21.0    51.0      4.0     16.0    16.0    24.0   11.0   19.0     9.0   15.0     8.0     5.0   16.0    23.0    55.0      8.0     22.0    17.0    21.0   12.0   22.0    10.0   14.0     9.0     4.0   23.0        9.0    1
242973    2025     120       1433      71.0       1182      62.0      0    23.0    55.0      8.0     22.0    17.0    21.0   12.0   22.0    10.0   14.0     9.0     4.0   23.0    21.0    51.0      4.0     16.0    16.0    24.0   11.0   19.0     9.0   15.0     8.0     5.0   16.0       -9.0    0